import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Eye, HeartHandshake, ShieldCheck, Sprout } from "lucide-react";
import { PageHero } from "@/components/layout/PageHero";

const values = [
  ["Stewardship", "We equip young people with the skills and confidence to pursue dignified livelihoods.", Sprout],
  ["Compassion", "We are rooted in Christian values of service, care and respect for every person.", HeartHandshake],
  ["Accountability", "We take responsibility for our decisions, resources and programme outcomes.", ShieldCheck],
  ["Transparency", "We communicate openly with communities, partners and supporters.", Eye],
];
const mandate = ["Empower women and youth through business skills and employability programmes.", "Promote quality education and support retention for vulnerable children.", "Safeguard children through community-led protection systems.", "Strengthen household livelihoods through savings and entrepreneurship support.", "Conserve the environment through climate-smart and restoration initiatives."];
const team = [["Shujaa Caroline Menach, HSC.", "Executive Director"], ["Abiagel Moraa", "Program Manager"], ["Victor Maosi", "Finance Officer"], ["Ruth Akoule", "Program Reporting Officer"], ["Lilian Mnagei", "Community Lead & Focal Liaison Officer"]];
const partners = [
  ["Global Give Back Circle (GGBC)", "/images/logo/gb.png"], ["Mastercard Foundation", "/images/logo/images.jpeg"], ["Circle Group", "/images/logo/Circle Group.jpg"], ["International Tree Foundation (ITF)", "/images/logo/itf.jpg"], ["Mekuno Project", "/images/logo/ms.png"]
];

export default function AboutPage() {
  return <>
    <PageHero eyebrow="Who we are" title="Hope grows when communities lead." description="A women-led, youth-serving and child-focused organisation working alongside communities across West Pokot County." imageSrc="/images/new/photo_45_2026-03-03_11-10-37.jpg" />
    <section className="bg-[#f4f1e9] py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-brandGreen">Our story</p><div className="relative mt-6 aspect-[4/3] overflow-hidden rounded-[1.5rem]"><Image src="/images/new/photo_40_2026-03-03_11-10-37.jpg" alt="Community members in West Pokot" fill className="object-cover" sizes="(min-width:1024px) 30vw, 100vw" /></div></div><div><h2 className="font-serif text-4xl leading-tight text-brandBlue sm:text-5xl">Rooted in West Pokot. Working toward a future where every person can flourish.</h2><p className="mt-7 max-w-2xl text-lg leading-relaxed text-slate-600">Founded in 2014 and formally registered in 2021, Perur Rays of Hope partners with communities to strengthen social justice, education, livelihoods and environmental resilience.</p></div></div></section>
    <section className="bg-white py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><article className="rounded-[2rem] bg-brandBlue p-8 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Our vision</p><p className="mt-7 font-serif text-4xl leading-tight">A resilient and empowered community.</p></article><article className="rounded-[2rem] bg-brandGreen p-8 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Our mission</p><p className="mt-7 font-serif text-3xl leading-tight">Safeguarding children, empowering youth and women, and conserving the environment for resilient livelihoods.</p></article></div></section>
    <section className="bg-brandBlue py-20 text-white sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-amber-300">Our commitment</p><h2 className="mt-5 font-serif text-4xl leading-tight sm:text-5xl">Change that holds together.</h2></div><ul className="space-y-5">{mandate.map((item, i) => <li key={item} className="flex gap-5 border-b border-white/20 pb-5"><span className="font-serif text-2xl text-amber-300">0{i + 1}</span><span className="pt-1 text-lg leading-relaxed text-white/85">{item}</span></li>)}</ul></div></section>
    <section className="bg-white py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-brandGreen">How we show up</p><h2 className="mt-4 font-serif text-4xl text-brandBlue sm:text-5xl">Values in practice.</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map(([title, text, Icon]) => { const ValueIcon = Icon as typeof Sprout; return <article key={title as string} className="border-t-2 border-brandGreen bg-[#f4f1e9] p-6"><ValueIcon className="h-6 w-6 text-brandGreen" /><h3 className="mt-8 font-serif text-2xl text-brandBlue">{title as string}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{text as string}</p></article>; })}</div></div></section>
    <section className="bg-[#f4f1e9] py-20 sm:py-28"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-brandGreen">Our people</p><h2 className="mt-4 font-serif text-4xl text-brandBlue sm:text-5xl">The team behind the work.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{team.map(([name, role], i) => <article key={name} className="bg-white p-7"><p className="font-serif text-3xl text-slate-200">0{i + 1}</p><h3 className="mt-10 text-lg font-bold text-brandBlue">{name}</h3><p className="mt-1 text-sm text-brandGreen">{role}</p></article>)}</div></div></section>
    <section className="bg-white py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-brandGreen">Working together</p><h2 className="mt-4 font-serif text-4xl text-brandBlue">Partners in possibility.</h2></div><Link href="/get-involved" className="inline-flex items-center gap-2 text-sm font-bold text-brandBlue hover:text-brandGreen">Partner with us <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-10 grid grid-cols-2 gap-px bg-slate-200 sm:grid-cols-3 lg:grid-cols-5">{partners.map(([name, logo]) => <div key={name} className="relative h-28 bg-white p-5"><Image src={logo} alt={`${name} logo`} fill className="p-5 object-contain" /></div>)}</div></div></section>
  </>;
}
